{% set name = "idna" %}
{% set version = "2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3cb5ce08046c4e3a560fc02f138d0ac63e00f8ce5901a56b32ec8b7994082aab

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - idna

about:
  home: https://github.com/kjd/idna
  license: BSD Like
  license_file: LICENSE.rst
  summary: Internationalized Domain Names in Applications (IDNA).
  description: |
    A library to support the Internationalised Domain Names in Applications
    (IDNA) protocol as specified in RFC 5891. This version of the protocol
    is often referred to as “IDNA2008”.

extra:
  recipe-maintainers:
    - goanpeca
    - jschueller
