travis:
  secure:
    BINSTAR_TOKEN: E92pVcL4jK73smaNffi58cXTJzJp+KKz5laWDT2AEJ2y4FNjD00JDsiGrRujeaJROFBX/m2IH8y1dTimnp1FCUj3f9UuRV3ufj9FBud1XE01PyOfcbIXzl/FwGzXUSj/ZNr0EYY1Mcx/qK1zH9OLc3IVe8TfMSGMoJGhZ+cCQ5Zy2DHCxzNt/gnU3Pqvr7PsoiqQ1Y5GHIUfCM6/rsLIbCrXTm/zmnH4Q9JK7vjh7/fVWq3vPgE6f6oD/Ycetuc7DrWOO6Oo2zX1C0w9lAXNl4vQSKJwRn5KUdgc8JL8G8wGrfNqKsm/h7sGN8/8IzixeXzkEbtYwwGSKvygR6VPy036UrW5ykyMR0Ak6WP/82JuhmSinR+EJYvSIbtGHQQza8CSNjJ9SJ7dx9Qlv44m2iQYgLLJz1MXdJDwkRn3E7JLwbK8wDoaIRnnuXwLCzVh+SHvT5nX9iYZzivHb1TrVXFBIRNbs2rW6Iv2W5KlWXn7iOrRKdjM2WaFeGuV23zADkF1+fLJzINz3Ux8Tcu6OYrWvCyZi2fIhxJeD/qE3qhti9cllej0shhGTAx/mxcFuH04Wv114KfZ0tXbfEAF7O2kuk4xecmWsLiPdn3yw778trZbIR8Gvqt05sRxEjePj+30B/4dJoJ9cxCDNb65z7mwf5lFySU2XftzKN2coJU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
